version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - |
        cat <<EOT >> "./.env"
        REPORT_API_ENDPOINT="$REPORT_API_ENDPOINT"
        REPORT_API_KEY="$REPORT_API_KEY"
        NEXT_PUBLIC_HOSTING_PATH="$NEXT_PUBLIC_HOSTING_PATH"
        EMAIL_HOST="$EMAIL_HOST"
        EMAIL_USER="$EMAIL_USER"
        EMAIL_PASS="$EMAIL_PASS"
        USE_LOCAL_CMS_DATA="$USE_LOCAL_CMS_DATA"
        CMS_API_ENDPOINT="$CMS_API_ENDPOINT"
        ENQUIRY_RECIPIENT_EMAIL="$ENQUIRY_RECIPIENT_EMAIL"
        EOT
      - |
        cat <<EOT >> "./corp_site"
        server {
          listen 80;
          listen [::]:80;
          server_name localhost;

          location / {
            proxy_pass http://0.0.0.0:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host \$host;
            proxy_cache_bypass \$http_upgrade;
            add_header X-Frame-Options SAMEORIGIN;
          }
        }
        EOT
      - yarn
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes