
export const links = {
  home: '/',
  about: '/about-us',
  aboutVision: '/about-us#mission',
  aboutUsProfile: '/about-us-profile',
  bussinessOverview: '/business-overview',
  productsSecurities: '/products/products-securities',
  productsFutures: '/products/products-futures',
  productInfo:'',
  newStockInfo:'/customer-services/new-stock-info',
  servicesCharges:'/customer-services/services-charges',
  importantNotice:'/customer-services/important-notices',
  fundDeposites:'/customer-services/fund-deposits',
  loanRatio:'/customer-services/loan_ratio',
  formDownload:'/customer-services/form-download',
  bankInfo:'/customer-services/bank-info',
  fps:'/customer-services/deposit-fps',
  qa:'/customer-services/qa',
  tradeTips:'/info/info',
  hkTradeTips:'/info/hk-stock',
  usTradeTips:'/info/us-stock',
  globalTradeTips:'/info/global-stock',
  ssTradeTips:'/info/ss-stock',
  hkMarginableStock:'/info/hk-marginable-stock',
  sseMarginableStock:'/info/sse-marginable-stock',
  szseMarginableStock:'/info/szse-marginable-stock',
  futuresAccount:'/info/futures-account',
  aboutCulture: '/about-us#culture',
  aboutLeadership: '/about-us#leadership',
  aboutTechFin: '/about-us#tech-fin',
  businessesAssetManagement: '/businesses/asset-management',
  businessesInvestmentBanking: '/businesses/investment-banking',
  businessesInsuranceBrokerage: '/businesses/insurance-brokerage',
  businessesSecuritiesBrokerage: '/businesses/global-markets',
  businessesEsg: '/businesses/esg-advisory',
  businessesArtazine: '/businesses/wealth_management',
  investor: '/investor-relations',
  investorCirculars: '/investor-relations/circulars',
  investorListingDocuments: '/investor-relations/listing-documents',
  investorCorporateInformation: '/investor-relations/corporate-information',
  investorInterimAnnualReports: '/investor-relations/interim-annual-reports',
  investorResultAnnouncements: '/investor-relations/results-announcements',
  investorAnnouncementsNotices: '/investor-relations/announcements-notices',
  investorFinCalendar: '/investor-relations/fin-calendar',
  investorEsg: '/investor-relations/esg',
  investPress: '/investor-relations/press',
  media: '/media-centre',
  mediaBlog: '/media-centre',
  mediaPress: '/media-centre/press',
  mediaBlogPost: '/media-centre/blog-post',
  mediaPressPost: '/media-centre/press-post',
  joinUs: '/join-us',
  joinUsFrontOffice: '/join-us/front-office',
  joinUsMiddleAndBackOffice: '/join-us/middle-and-back-office',
  jobOpening: '/job-opening',
  contact: '/contact-us',
  disclaimer: '/disclaimer',
  privacy_policy: '/privacy-policy',
}
