export const links = {
  home: '/',
  about: '/about',
  aboutVision: '/about#mission',
  aboutCulture: '/about#culture',
  aboutLeadership: '/about#leadership',
  aboutTechFin: '/about#tech-fin',
  businesses: '/businesses',
  businessesSecurities: '/businesses/securities',
  businessesWeb3: '/businesses/web3-media',
  investor: '/investor-relations',
  investorFinReport: '/investor-relations/fin-report',
  investorFinCalendar: '/investor-relations/fin-calendar',
  investorEsg: '/investor-relations/esg',
  media: '/media-centre',
  mediaBlog: '/media-centre',
  mediaPress: '/media-centre/press',
  mediaBlogPost: '/media-centre/blog-post',
  mediaPressPost: '/media-centre/press-post',
  contact: '/contact',
}
